---
engines:
  fixme:
    enabled: false
  pep8:
    enabled: false
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
ratings:
  paths:
  - "**.py"
exclude_paths:
- testsuite/**
